This file extracts data that is needed from the population dataset which is in excel form, filter out unuseful rows and columns, set column names, and convert and save the file into csv format

In [7]:
import pandas as pd


df=pd.read_excel("../data/raw/population.xlsx","Table 1")

In [38]:
# find the labels for the columns
areaName=df.iloc[6,:10]
populationYear=df.iloc[5,10:]
col=areaName.append(populationYear)

/tmp/ipykernel_3870/1809354427.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  col=areaName.append(populationYear)

In [39]:
col=list(col)
col

['S/T code',
 'S/T name',
 'GCCSA code',
 'GCCSA name',
 'SA4 code',
 'SA4 name',
 'SA3 code',
 'SA3 name',
 'SA2 code',
 'SA2 name',
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 nan,
 '2011-2021',
 nan,
 nan,
 'Area',
 'Population density 2021']

In [40]:
# remove column names for two columns that dont have any values
col.pop(31)

nan

In [46]:
col.pop(33)

nan

In [47]:
col

['S/T code',
 'S/T name',
 'GCCSA code',
 'GCCSA name',
 'SA4 code',
 'SA4 name',
 'SA3 code',
 'SA3 name',
 'SA2 code',
 'SA2 name',
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 '2011-2021',
 nan,
 'Area',
 'Population density 2021']

In [49]:
# finalize column names 
col[31]=col[31]+"no"

In [51]:
col[32]="2011-2021%"

In [52]:
col

['S/T code',
 'S/T name',
 'GCCSA code',
 'GCCSA name',
 'SA4 code',
 'SA4 name',
 'SA3 code',
 'SA3 name',
 'SA2 code',
 'SA2 name',
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 '2011-2021no',
 '2011-2021%',
 'Area',
 'Population density 2021']

In [21]:
#check labels of different columns
df.iloc[5:,:]

,Australian Bureau of Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2018,2019,2020,2021,NaN,2011-2021,NaN,NaN,Area,Population density 2021
6,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,no.,no.,no.,no.,NaN,no.,%,NaN,km2,persons/km2
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021007,Braidwood,...,4140,4211,4273,4330,NaN,872,25.2,NaN,3418.4,1.3
9,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021008,Karabar,...,8507,8488,8519,8546,NaN,-546,-6,NaN,7,1223.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2466,"Source: Regional population, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2468,© Commonwealth of Australia 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# filter out the values, the values begin from row 8
df1=df.iloc[8:,:]
df1

,Australian Bureau of Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
8,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021007,Braidwood,...,4140,4211,4273,4330,NaN,872,25.2,NaN,3418.4,1.3
9,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021008,Karabar,...,8507,8488,8519,8546,NaN,-546,-6,NaN,7,1223.9
10,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021009,Queanbeyan,...,11447,11450,11437,11370,NaN,655,6.1,NaN,4.8,2387.7
11,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021010,Queanbeyan - East,...,5072,5117,5077,5093,NaN,142,2.9,NaN,13,391.7
12,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021012,Queanbeyan West - Jerrabomberra,...,13008,12935,12796,12743,NaN,-480,-3.6,NaN,13.7,931.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2466,"Source: Regional population, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2468,© Commonwealth of Australia 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# remove columns with no data
df1=df1.drop(["Unnamed: 31","Unnamed: 34"],axis=1)

In [54]:
origName=df1.columns
origName

Index(['            Australian Bureau of Statistics', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 35', 'Unnamed: 36'],
      dtype='object')

In [55]:
# create dictionary with original column names and actual column names
res = {}
for key in origName:
    for value in col:
        res[key] = value
        col.remove(value)
        break  

res

{'            Australian Bureau of Statistics': 'S/T code',
 'Unnamed: 1': 'S/T name',
 'Unnamed: 2': 'GCCSA code',
 'Unnamed: 3': 'GCCSA name',
 'Unnamed: 4': 'SA4 code',
 'Unnamed: 5': 'SA4 name',
 'Unnamed: 6': 'SA3 code',
 'Unnamed: 7': 'SA3 name',
 'Unnamed: 8': 'SA2 code',
 'Unnamed: 9': 'SA2 name',
 'Unnamed: 10': 2001,
 'Unnamed: 11': 2002,
 'Unnamed: 12': 2003,
 'Unnamed: 13': 2004,
 'Unnamed: 14': 2005,
 'Unnamed: 15': 2006,
 'Unnamed: 16': 2007,
 'Unnamed: 17': 2008,
 'Unnamed: 18': 2009,
 'Unnamed: 19': 2010,
 'Unnamed: 20': 2011,
 'Unnamed: 21': 2012,
 'Unnamed: 22': 2013,
 'Unnamed: 23': 2014,
 'Unnamed: 24': 2015,
 'Unnamed: 25': 2016,
 'Unnamed: 26': 2017,
 'Unnamed: 27': 2018,
 'Unnamed: 28': 2019,
 'Unnamed: 29': 2020,
 'Unnamed: 30': 2021,
 'Unnamed: 32': '2011-2021no',
 'Unnamed: 33': '2011-2021%',
 'Unnamed: 35': 'Area',
 'Unnamed: 36': 'Population density 2021'}

In [58]:
# change the column names of the dataframe
df1=df1.rename(columns=res)
df1

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,2016,2017,2018,2019,2020,2021,2011-2021no,2011-2021%,Area,Population density 2021
8,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021007,Braidwood,...,3950,4039,4140,4211,4273,4330,872,25.2,3418.4,1.3
9,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021008,Karabar,...,8531,8526,8507,8488,8519,8546,-546,-6,7,1223.9
10,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021009,Queanbeyan,...,11230,11355,11447,11450,11437,11370,655,6.1,4.8,2387.7
11,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021010,Queanbeyan - East,...,4970,5013,5072,5117,5077,5093,142,2.9,13,391.7
12,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021012,Queanbeyan West - Jerrabomberra,...,13150,13083,13008,12935,12796,12743,-480,-3.6,13.7,931.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2466,"Source: Regional population, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2468,© Commonwealth of Australia 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
# filter out datas thats in victoria

df1=df1.loc[df1["S/T code"]==2]
df1

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,2016,2017,2018,2019,2020,2021,2011-2021no,2011-2021%,Area,Population density 2021
650,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011001,Alfredton,...,11852,12639,13520,14408,15472,16823,8371,99,52.7,319.2
651,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011002,Ballarat,...,12301,12261,12237,12311,12183,12076,-289,-2.3,12.4,975.5
652,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011005,Buninyong,...,7311,7407,7413,7452,7369,7232,507,7.5,51.6,140.2
653,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011006,Delacombe,...,7195,7617,8174,8876,9736,10640,4802,82.3,34.2,311.5
654,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011007,Smythes Creek,...,3990,4002,4040,4109,4148,4213,394,10.3,104.7,40.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21703,Colac - Corangamite,217031476,Otway,...,3556,3633,3707,3797,3905,3978,558,16.3,1505.9,2.6
1168,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041477,Moyne - East,...,6709,6714,6741,6790,6873,6989,210,3.1,3275.8,2.1
1169,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041478,Moyne - West,...,9603,9681,9773,9833,9842,9963,939,10.4,2037.8,4.9
1170,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041479,Warrnambool - North,...,21442,21676,21934,22157,22379,22462,2583,13,62.4,359.9
1171,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041480,Warrnambool - South,...,13173,13192,13214,13247,13323,13292,151,1.1,120.2,110.6

In [65]:
df1.to_csv('../data/curated/population.csv',index=False)

In [66]:
df= pd.read_csv('../data/curated/population.csv')
df

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,2016,2017,2018,2019,2020,2021,2011-2021no,2011-2021%,Area,Population density 2021
0,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011001,Alfredton,...,11852,12639,13520,14408,15472,16823,8371,99.0,52.7,319.2
1,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011002,Ballarat,...,12301,12261,12237,12311,12183,12076,-289,-2.3,12.4,975.5
2,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011005,Buninyong,...,7311,7407,7413,7452,7369,7232,507,7.5,51.6,140.2
3,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011006,Delacombe,...,7195,7617,8174,8876,9736,10640,4802,82.3,34.2,311.5
4,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011007,Smythes Creek,...,3990,4002,4040,4109,4148,4213,394,10.3,104.7,40.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21703,Colac - Corangamite,217031476,Otway,...,3556,3633,3707,3797,3905,3978,558,16.3,1505.9,2.6
518,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041477,Moyne - East,...,6709,6714,6741,6790,6873,6989,210,3.1,3275.8,2.1
519,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041478,Moyne - West,...,9603,9681,9773,9833,9842,9963,939,10.4,2037.8,4.9
520,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041479,Warrnambool - North,...,21442,21676,21934,22157,22379,22462,2583,13.0,62.4,359.9
521,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041480,Warrnambool - South,...,13173,13192,13214,13247,13323,13292,151,1.1,120.2,110.6